//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int Auditoria_ID { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string TablaAfectada { get; set; }
        public string Operacion { get; set; }
        public string ID_Modificado { get; set; }
        public string DatoAntiguo { get; set; }
        public string DatoNuevo { get; set; }
    }
}
