//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Pagos = new List<Pago>();
        }
    
        public string Cli_Cedula { get; set; }
        public string Cli_Nombre { get; set; }
        public string Cli_Apellido { get; set; }
        public Nullable<System.DateTime> Cli_BirthDate { get; set; }
        public string Cli_Pais { get; set; }
        public string Cli_Email { get; set; }
        public Nullable<bool> Cli_LogicalDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Pago> Pagos { get; set; }
    }
}
