//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int Pago_ID { get; set; }
        public string Pago_Codigo { get; set; }
        public string Cli_Cedula { get; set; }
        public string Sus_ID { get; set; }
        public Nullable<decimal> Pago_Monto { get; set; }
        public Nullable<System.DateTime> Pago_Fecha { get; set; }
        public string Pago_Estado { get; set; }
        public Nullable<bool> Pago_LogicalDelete { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Suscripcion Suscripcion { get; set; }
    }
}
