//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan()
        {
            this.Suscripcions = new List<Suscripcion>();
        }
    
        public int Plan_ID { get; set; }
        public string Plan_Nombre { get; set; }
        public string Plan_Duracion { get; set; }
        public Nullable<decimal> Plan_Precio { get; set; }
        public string Plan_Plataforma { get; set; }
        public Nullable<bool> Plan_LogicalDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Suscripcion> Suscripcions { get; set; }
    }
}
