//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suscripcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suscripcion()
        {
            this.Pagos = new List<Pago>();
        }
    
        public string Sus_ID { get; set; }
        public int Plan_ID { get; set; }
        public Nullable<System.DateTime> Sus_StartDate { get; set; }
        public Nullable<System.DateTime> Sus_EndDate { get; set; }
        public string Sus_Estado { get; set; }
        public Nullable<bool> Sus_RenovacionAuto { get; set; }
        public Nullable<bool> Sus_LogicalDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Pago> Pagos { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
